HollowCreativePlots:
  Version: 1.0.0
  creative_world: creative_plots
  main_world: NewWorld
  IgnoredMaterials:
  - BUTTON
  - DOOR
  - FENCE
  - FENCE_GATE
  - LEAVES
  - LOG
  - PLANK
  - SIGN
  - SLAB
  - STAIRS
  - TRAPDOOR
  - WOOD
  - AIR
  - ANDESITE
  - DIORITE
  - GRANITE
  - DIRT
  - GRAVEL
  - CONCRETE
  - TERRACOTTA
  - WOOL
  - BANNER
  - CARPET
  - BED
  - BRICK
  - CAULDRON
  - CHEST
  - STONE
  - CLAY
  - LADDER
  - SCAFFOLDING
  - FIRE
  - STRING
  - GRASS
  - WATER
  - SAPLING
  - ALLIUM
  - AZURE_BLUET
  - TULIP
  - ROSE
  - MUSHROOM
  - COBWEB
  - FERN
  - CORNFLOWER
  - DANDELION
  - DEAD
  - FARMLAND
  - GLASS
  - HAY_BLOCK
  - LEVER
  - LILAC
  - LILY
  - NETHERRACK
  - DAISY
  - PEONY
  - PODZOL
  - MYCELIUM
  - POPPY
  - PRISMARINE
  - QUARTZ
  - SAND
  - SUNFLOWER
  - ICE
  - VINE
  - WHEAT
  - BASALT
  - PLAYER
  - POT
  - SNOW
  - LAPIS
  - SUGAR_CANE
  - KELP
  - BAMBOO
  - OBSIDIAN
  - TABLE
  - FURNACE
  - PLATE
  - RAIL
  - CHAIN
  - IRON_BARS
  - TRIPWIRE
  - DAYLIGHT
  - DROPPER
  - BARRIER
  - MAGMA
  - WART
  - CORAL
  - REPEATER
  - COMPARATOR
  - JIGSAW
  - STAND
  - SKULL
  - LOOM
  - COMPOSTER
  - BARREL
  - SMOKER
  - LECTERN
  - BELL
  - LANTERN
  - TARGET
  - LAVA
  - TORCH
  - STEM
  - COCOA
  - CARROTS
  - BEETROOTS
  - BUBBLE
  - SWEET_BERRY
  - NYLIUM
  - HYPHAE
  - DISPENSER
  - NOTE_BLOCK
  - PISTON
  - PICKLE
  - ORCHID
  - FUNGUS
  - SPROUTS
  - BOOKSHELF
  - PURPUR
  - CACTUS
  - JUKEBOX
  - PUMPKIN
  - SOUL
  - MELON
  - ANVIL
  - BONE
  - OBSERVER
  - CAKE
  - SHROOMLIGH
  - SLATE
  - CALCITE
  - TUFF
  - CORAL
  - COPPER
  - ROOTS
  - DRIPLEAF
  - MOSS
  - LICHEN
  - LIGHTNING_ROD
  - SENSOR
  - CANDLE